# Generated by Django 4.2 on 2024-07-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, max_length=256, null=True)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'base_client',
                'ordering': ('logo_url',),
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_label', models.CharField(blank=True, max_length=64, null=True)),
                ('community_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'community',
                'verbose_name_plural': 'communities',
                'db_table': 'base_community',
                'ordering': ('email_label',),
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'db_table': 'base_consultation',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CustomersHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=62, null=True)),
                ('side_heading', models.CharField(blank=True, max_length=32, null=True)),
                ('image_url', models.URLField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'customersHeading',
                'verbose_name_plural': 'customersHeadings',
                'db_table': 'base_customersHeading',
                'ordering': ('side_heading',),
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('company_name', models.CharField(blank=True, max_length=64, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'logo',
                'verbose_name_plural': 'logos',
                'db_table': 'base_logo',
                'ordering': ('company_name',),
            },
        ),
        migrations.CreateModel(
            name='MainHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted_text', models.CharField(blank=True, max_length=128, null=True)),
                ('text', models.CharField(blank=True, max_length=128, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'mainHeading',
                'verbose_name_plural': 'mainHeadings',
                'db_table': 'base_mainHeading',
                'ordering': ('text',),
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_no', models.IntegerField(blank=True, null=True)),
                ('index_title', models.CharField(blank=True, max_length=64, null=True)),
                ('slider_note', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'mainSlider',
                'verbose_name_plural': 'videos',
                'db_table': 'base_mainSlider',
                'ordering': ('index_title',),
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_name', models.SlugField(blank=True, max_length=32, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'navbar',
                'verbose_name_plural': 'navbar',
                'db_table': 'base_navbar',
                'ordering': ('navbar_name',),
            },
        ),
        migrations.CreateModel(
            name='NewsHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=128, null=True)),
                ('side_heading', models.CharField(blank=True, max_length=32, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'newsHeading',
                'verbose_name_plural': 'newsHeadings',
                'db_table': 'base_newsHeading',
                'ordering': ('side_heading',),
            },
        ),
        migrations.CreateModel(
            name='NewsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_heading', models.CharField(blank=True, max_length=64, null=True)),
                ('slider_paragraph', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'newsSlider',
                'verbose_name_plural': 'newsSliders',
                'db_table': 'base_newsSlider',
                'ordering': ('slider_heading',),
            },
        ),
        migrations.CreateModel(
            name='TechHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=128, null=True)),
                ('highlighted_text', models.CharField(blank=True, max_length=128, null=True)),
                ('side_heading', models.CharField(blank=True, max_length=32, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'techHeading',
                'verbose_name_plural': 'techHeadings',
                'db_table': 'base_techHeading',
                'ordering': ('text',),
            },
        ),
        migrations.CreateModel(
            name='TechSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_notes', models.TextField(blank=True, null=True)),
                ('tech_logo_url', models.URLField(blank=True, max_length=256, null=True)),
                ('tech_logo_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'techSlider',
                'verbose_name_plural': 'techSliders',
                'db_table': 'base_techSlider',
                'ordering': ('tech_notes',),
            },
        ),
        migrations.CreateModel(
            name='Vedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='')),
                ('video_title', models.CharField(blank=True, max_length=64, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'db_table': 'base_video',
                'ordering': ('video_title',),
            },
        ),
    ]
